import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';

import '../models/script_entry.dart';

enum ScriptExportFormat {
  fountain,
  plainText,
}

typedef ShareScriptTextFn = Future<void> Function(
  String text, {
  required String subject,
  required String title,
});
typedef SetClipboardTextFn = Future<void> Function(String text);

class ScriptExportDocument {
  const ScriptExportDocument({
    required this.title,
    required this.subject,
    required this.text,
  });

  final String title;
  final String subject;
  final String text;
}

class ScriptExportService {
  ScriptExportService({
    ShareScriptTextFn? shareText,
    SetClipboardTextFn? setClipboard,
  })  : _shareText = shareText ?? _defaultShareText,
        _setClipboard = setClipboard ?? _defaultSetClipboard;

  final ShareScriptTextFn _shareText;
  final SetClipboardTextFn _setClipboard;

  ScriptExportDocument buildDocument({
    required ScriptExportFormat format,
    required List<ScriptEntry> entries,
    required String title,
    DateTime? capturedAt,
    String notes = '',
  }) {
    final cleanedEntries = entries
        .where((entry) => entry.text.trim().isNotEmpty)
        .toList(growable: false);
    final exportTitle = title.trim().isEmpty ? 'Ghosteye Take' : title.trim();
    final trimmedNotes = notes.trim();
    final subject = '$exportTitle (${_formatName(format)})';
    final text = switch (format) {
      ScriptExportFormat.fountain =>
        _buildFountain(cleanedEntries, exportTitle, capturedAt, trimmedNotes),
      ScriptExportFormat.plainText =>
        _buildPlainText(cleanedEntries, exportTitle, capturedAt, trimmedNotes),
    };

    return ScriptExportDocument(
      title: exportTitle,
      subject: subject,
      text: text,
    );
  }

  Future<void> shareDocument({
    required ScriptExportFormat format,
    required List<ScriptEntry> entries,
    required String title,
    DateTime? capturedAt,
    String notes = '',
  }) async {
    final document = buildDocument(
      format: format,
      entries: entries,
      title: title,
      capturedAt: capturedAt,
      notes: notes,
    );
    await _shareText(
      document.text,
      subject: document.subject,
      title: document.title,
    );
  }

  Future<void> copyDocument({
    required ScriptExportFormat format,
    required List<ScriptEntry> entries,
    required String title,
    DateTime? capturedAt,
    String notes = '',
  }) async {
    final document = buildDocument(
      format: format,
      entries: entries,
      title: title,
      capturedAt: capturedAt,
      notes: notes,
    );
    await _setClipboard(document.text);
  }

  static String _buildFountain(
    List<ScriptEntry> entries,
    String title,
    DateTime? capturedAt,
    String notes,
  ) {
    final buffer = StringBuffer()
      ..writeln('Title: $title')
      ..writeln('Credit: Generated by Ghosteye');

    if (capturedAt != null) {
      buffer.writeln('Draft date: ${_formatTimestamp(capturedAt)}');
    }

    buffer.writeln();

    if (entries.isEmpty) {
      buffer.writeln('/* No screenplay lines captured yet. */');
    } else {
      for (var index = 0; index < entries.length; index++) {
        final entry = entries[index];
        buffer.writeln(entry.text);

        final nextType =
            index + 1 < entries.length ? entries[index + 1].type : null;
        final shouldInsertBlankLine = switch (entry.type) {
          ScriptEntryType.slugline || ScriptEntryType.action => true,
          ScriptEntryType.dialogue => nextType != ScriptEntryType.dialogue &&
              nextType != ScriptEntryType.parenthetical,
          ScriptEntryType.character || ScriptEntryType.parenthetical => false,
        };

        if (shouldInsertBlankLine) {
          buffer.writeln();
        }
      }
    }

    if (notes.isNotEmpty) {
      buffer
        ..writeln()
        ..writeln('/*')
        ..writeln('Notes:')
        ..writeln(notes)
        ..writeln('*/');
    }

    return buffer.toString().trimRight();
  }

  static String _buildPlainText(
    List<ScriptEntry> entries,
    String title,
    DateTime? capturedAt,
    String notes,
  ) {
    final buffer = StringBuffer()..writeln(title);
    if (capturedAt != null) {
      buffer.writeln('Captured: ${_formatTimestamp(capturedAt)}');
    }
    buffer
      ..writeln('Lines: ${entries.length}')
      ..writeln();

    if (entries.isEmpty) {
      buffer.writeln('No screenplay lines captured yet.');
    } else {
      for (final entry in entries) {
        buffer.writeln(
          switch (entry.type) {
            ScriptEntryType.slugline => 'Scene: ${entry.text}',
            ScriptEntryType.action => entry.text,
            ScriptEntryType.character => 'Character: ${entry.text}',
            ScriptEntryType.dialogue => entry.text,
            ScriptEntryType.parenthetical => entry.text,
          },
        );
      }
    }

    if (notes.isNotEmpty) {
      buffer
        ..writeln()
        ..writeln('Notes:')
        ..writeln(notes);
    }

    return buffer.toString().trimRight();
  }

  static String _formatName(ScriptExportFormat format) {
    return switch (format) {
      ScriptExportFormat.fountain => 'Fountain',
      ScriptExportFormat.plainText => 'Plain Text',
    };
  }

  static String _formatTimestamp(DateTime value) {
    final utc = value.toUtc();
    final month = utc.month.toString().padLeft(2, '0');
    final day = utc.day.toString().padLeft(2, '0');
    final hour = utc.hour.toString().padLeft(2, '0');
    final minute = utc.minute.toString().padLeft(2, '0');
    return '${utc.year}-$month-$day $hour:$minute UTC';
  }

  static Future<void> _defaultShareText(
    String text, {
    required String subject,
    required String title,
  }) async {
    await SharePlus.instance.share(
      ShareParams(
        text: text,
        subject: subject,
        title: title,
      ),
    );
  }

  static Future<void> _defaultSetClipboard(String text) async {
    await Clipboard.setData(ClipboardData(text: text));
  }
}
