import 'package:flutter_test/flutter_test.dart';
import 'package:ghosteye/models/script_entry.dart';
import 'package:ghosteye/services/script_export_service.dart';

void main() {
  const entries = <ScriptEntry>[
    ScriptEntry(
      type: ScriptEntryType.slugline,
      text: 'INT. CAB - NIGHT',
    ),
    ScriptEntry(
      type: ScriptEntryType.action,
      text: 'Streetlight fractures over the windshield.',
    ),
    ScriptEntry(
      type: ScriptEntryType.character,
      text: 'MARA',
    ),
    ScriptEntry(
      type: ScriptEntryType.dialogue,
      text: 'Keep the lens steady.',
    ),
  ];

  test('buildDocument formats Fountain output with screenplay headers', () {
    final service = ScriptExportService();

    final document = service.buildDocument(
      format: ScriptExportFormat.fountain,
      entries: entries,
      title: 'Current take',
      capturedAt: DateTime.utc(2026, 4, 23, 4, 30),
    );

    expect(document.subject, 'Current take (Fountain)');
    expect(document.text, contains('Title: Current take'));
    expect(document.text, contains('Credit: Generated by Ghosteye'));
    expect(document.text, contains('INT. CAB - NIGHT'));
    expect(document.text, contains('MARA'));
    expect(document.text, contains('Keep the lens steady.'));
  });

  test('buildDocument formats plain-text output with readable labels', () {
    final service = ScriptExportService();

    final document = service.buildDocument(
      format: ScriptExportFormat.plainText,
      entries: entries,
      title: 'Saved take',
      capturedAt: DateTime.utc(2026, 4, 23, 4, 30),
    );

    expect(document.subject, 'Saved take (Plain Text)');
    expect(document.text, contains('Saved take'));
    expect(document.text, contains('Captured: 2026-04-23 04:30 UTC'));
    expect(document.text, contains('Lines: 4'));
    expect(document.text, contains('Scene: INT. CAB - NIGHT'));
    expect(document.text, contains('Character: MARA'));
  });

  test('buildDocument appends notes to Fountain output as a boneyard block',
      () {
    final service = ScriptExportService();

    final document = service.buildDocument(
      format: ScriptExportFormat.fountain,
      entries: entries,
      title: 'Current take',
      notes: 'Push in slowly on the second line.',
    );

    expect(document.text, contains('/*'));
    expect(document.text, contains('Notes:'));
    expect(document.text, contains('Push in slowly on the second line.'));
    expect(document.text.trimRight().endsWith('*/'), isTrue);
  });

  test('buildDocument appends notes to plain-text output', () {
    final service = ScriptExportService();

    final document = service.buildDocument(
      format: ScriptExportFormat.plainText,
      entries: entries,
      title: 'Saved take',
      notes: 'Reshoot wider.',
    );

    expect(document.text, contains('Notes:'));
    expect(document.text, contains('Reshoot wider.'));
  });

  test('buildDocument omits the notes section when notes are blank', () {
    final service = ScriptExportService();

    final document = service.buildDocument(
      format: ScriptExportFormat.plainText,
      entries: entries,
      title: 'Saved take',
      notes: '   ',
    );

    expect(document.text, isNot(contains('Notes:')));
  });

  test('shareDocument and copyDocument delegate formatted text', () async {
    String? sharedText;
    String? sharedSubject;
    String? clipboardText;

    final service = ScriptExportService(
      shareText: (text, {required subject, required title}) async {
        sharedText = text;
        sharedSubject = subject;
      },
      setClipboard: (text) async {
        clipboardText = text;
      },
    );

    await service.shareDocument(
      format: ScriptExportFormat.fountain,
      entries: entries,
      title: 'Current take',
    );
    await service.copyDocument(
      format: ScriptExportFormat.plainText,
      entries: entries,
      title: 'Current take',
    );

    expect(sharedSubject, 'Current take (Fountain)');
    expect(sharedText, contains('Title: Current take'));
    expect(clipboardText, contains('Scene: INT. CAB - NIGHT'));
  });
}
